version: "3.7"
services:
  rakuten_test1:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/rakuten_test
    image: rakuten_python
    command: python app.py
    container_name: "rakuten_test_container"